---
title: "Reproducing Kernel Hilbert Spaces - An Introduction"
date: 2025-09-19
categories: [Analysis]
bibliography: ../../references.bib
nocite: |
  @fukumizu2008kernel
  @berlinet2004reproducing
  @aronszajn1950theory
  @wiki:rkhs
---

### Introduction

This post is Part II of the series on Reproducing Kernel Hilbert Spaces (RKHS). We have so far looked at [Positive Definite Kernels](/posts/welcome): special functions $k(x,y)$ that produce Gram matrices that are positive semidefinite for any finite set of points. At first glance, this definition may feel a little abstract making us wonder why we should even care about kernels satisfying such an inequality.

One reason is that positive definite kernels secretly encode a hidden geometry: each kernel corresponds to a Hilbert space of functions, where the kernel itself acts as a sort of “building block.” This Hilbert space is what we call a Reproducing Kernel Hilbert Space (RKHS).

What makes an RKHS so interesting is the reproducing property. In an RKHS $\mathcal{H}$, evaluating a function at a point $x$ can be done by taking an inner product with a special function $k_x$ corresponding to that point: 
$$ f(x) = {\langle f, k_x \rangle}_{\mathcal{H}} $$

Why is it useful? Firstly it simply guarantees that point evaluation is always a nice, continuous operation (unlike in some spaces such as ${\mathcal{L}}^2$, where evaluation doesn’t even make sense). Secondly it lays the mathematical foundation for many mathematical applications including machine learning algorithms (like kernel methods and Gaussian processes), signal processing, approximation theory, and even parts of harmonic analysis rely substantially on RKHS.

In this post, we will understand the relation between positive definite kernels and reproducing kernel Hilbert spaces. We will see that every RKHS comes with a unique reproducing kernel which is positive definite, and that every positive definite kernel gives rise to a corresponding RKHS. 

## Reproducing Kernel Hilbert Spaces (RKHS)

> Let $\mathcal{X}$ be a set. A **reproducing kernel Hilbert space (RKHS)** over $\mathcal{X}$ is a Hilbert space $\mathcal{H}$ consisting of functions on $\mathcal{X}$ such that for each $x \in \mathcal{X}$ there is a function $k_x \in \mathcal{H}$ with the reproducing property
$$
\langle f, k_x \rangle_\mathcal{H} = f(x) \qquad ;\forall f \in \mathcal{H} \qquad .
$$
Considering $k(\cdot, x) = k_x(\cdot)$. The function $k$ is called a **reproducing kernel** of $\mathcal{H}$.

Simply speaking, the evaluation of any function from $\mathcal{H}$ at each $x \in \mathcal{X}$ is the same as taking the inner product of $f$ with a corresponding $k_x$ in $\mathcal{H}$. We will prove that the above reproducing kernel is in fact a positive definite kernel on $\mathcal{X}$. Firstly, applying the reproducing property above to the function $k(\cdot,x_j)$ (which is in $\mathcal{H}$) at the point $x_i$ we get: $k(x_i,x_j) = k_{x_j}(x_i) = {\langle k(\cdot,x_j), k(\cdot,x_i)\rangle}_{\mathcal{H}}$. We will use this equality in further proofs.

> Proposition 1: A reproducing kernel of a RKHS is a positive definite kernel on $X$.

> Proof: Using the above equality we obtain$$
\sum_{i,j=1}^n c_i \overline{c_j} k(x_i, x_j)
= \sum_{i,j=1}^n c_i \overline{c_j} \langle k(\cdot, x_j), k(\cdot, x_i) \rangle
= \left\langle \sum_{i=1}^n c_i k(\cdot, x_i), \sum_{j=1}^n c_j k(\cdot, x_j) \right\rangle
\geq 0
$$


Note that the reproducing kernel on a Hilbert space is unique if it exists. Suppose $k$ and $\tilde{k}$ are reproducing kernels. Then we have
$\widetilde{k}(x, y) = \langle \widetilde{k}(\cdot, y), k(\cdot, x) \rangle = \langle k(\cdot, x), \widetilde{k}(\cdot, y) \rangle = \overline{k(y, x)} = k(x, y)$.

Also note that $\|k(\cdot, x)\| = \sqrt{k(x, x)}$ since $\|k(\cdot, x)\|^2 = \langle k(\cdot, x), k(\cdot, x) \rangle = k(x, x)$.

At this point we might wonder why we care about this reproducing property and what it has to do with evaluation at a point. The key is that evaluation should be a nice operation. Like we noted before, in some Hilbert spaces of functions (like ${\mathcal{L}}^2$), evaluation doesn’t even make sense as two different-looking functions might represent the same element of the space making $f(x)$ ambiguous.

To avoid this, we require that the evaluation map $e_x(f) = f(x)$ to be a continuous linear functional for every point $x$. Once this condition holds, the Riesz representation theorem guarantees the existence of the kernel elements $k_x$ and the reproducing property follows naturally. In fact, the continuity of evaluation functions characterizes RKHS.

> Proposition 2: Let $\mathcal{H}$ be a Hilbert space consisting of functions on a set $\mathcal{X}$. Then $\mathcal{H}$ is a RKHS iff the evaluation map $e_x : \mathcal{H} \rightarrow \mathbb{F}, e_x(f) = f(x)$, is a continuous linear functional for each $x \in \mathcal{X}$.

> Proof: Assume $\mathcal{H}$ is a RKHS. We obtain the boundedness of $e_x$ from
> $$|e_x(f)| = |\langle f, k_x \rangle| \leq \|k_x\| \|f\|.$$
> Conversely, let's assume that the evaluation map is continuous. By Riesz representation theorem, there exists a $k_x \in \mathcal{H}$ such that
> $$\langle f, k_x \rangle = e_x(f) = f(x).$$

So far, we’ve seen the following two things:

- Every RKHS has a reproducing kernel which turns out to be positive definite.

- continuous evaluation functionals characterizing RKHS

The natural question now is: given just a positive definite kernel, can we always build the "corresponding" Hilbert space in some sense.

Turns out, every positive definite kernel corresponds to a unique RKHS. In other words, kernels are not just abstract inequalities, they actually encode entire Hilbert spaces of functions. Theorem 3 makes this precise.

> Theorem 3: Let $k : \mathcal{X} \times \mathcal{X} \to \mathbb{C}$ (or $\mathbb{R}$) be a positive definite kernel on a set $\mathcal{X}$. Then, there uniquely exists a RKHS $\mathcal{H}_k$ consisting of functions on $\mathcal{X}$ such that  
  > 1. $k(\cdot, x) \in \mathcal{H}_k$ for every $x \in \mathcal{X}$,  
  > 2. Span $\{k(\cdot, x) \mid x \in \mathcal{X}\}$ is dense in $\mathcal{H}_k$,  
  > 3. $k$ is a reproducing kernel on $\mathcal{H}_k$, i.e. $\langle f, k(\cdot, x) \rangle_{\mathcal{H}_k} = f(x),$ for all x \in \mathcal{X} and $f \in \mathcal{H}_k.$

Theorem 3 is the big result we were aiming for: every positive definite kernel actually generates a unique RKHS. This shows that kernels are not just abstract objects and that they encode entire function spaces with nice geometric properties. In the next post, we will probably dive into the proof and see exactly how this Hilbert space is constructed from the kernel. We will also look at some concrete examples of RKHS and explicitly write their reproducing kernels.

### References

