project:
  type: website
  output-dir: docs

website:
  title: "Mostly Mathematics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts
        text: Posts
  sidebar:
    style: "docked"
    contents: auto
    about:
      image: sun_about.jpg   # your image file
      text: |
       Getting better at math by communicating math.

format:
  html:
    theme: flatly
    css: styles.css
    
