project:
  type: website
  output-dir: docs
  resources:
    - references.bib

website:
  title: "Mostly Mathematics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      #- href: posts
      #  text: Posts
      #- text: Categories
        menu:
          - text: Algebra
            href: categories/algebra.qmd
          - text: Analysis
            href: categories/analysis.qmd
          - text: Topology
            href: categories/topology.qmd
          - text: Dynamics
            href: categories/dynamics.qmd
          - text: Complex Analysis
            href: categories/complex_analysis.qmd
          - text: Linear Algebra
            href: categories/linear_algebra.qmd
          - text: Probability
            href: categories/probability.qmd
          - text: Ergodic Theory
            href: categories/ergodic_theory.qmd
  sidebar:
    style: "docked"
    contents: auto
    #about:
     # image: images/sun_about.jpg   # your image file
      #text: |
      # Getting better at math by communicating math.

format:
  html:
    theme: flatly
    css: styles.css
    
    
