project:
  type: website
  output-dir: docs   # GitHub Pages will serve from here

website:
  title: "MostlyMathematics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts
        text: Posts
format:
  html:
    theme: cosmo
    css: styles.css
