---
title: "The Birkhoff's Ergodic Theorem"
date: "2025-09-10"
categories: [Analysis, Dynamics, Ergodic Theory]
bibliography: ../../references.bib
nocite: |
  @walters1982
  @silva2008
  @assani2003wiener
---

### Introduction

The ergodic theorem was proved in 1931, first by John von Neumann in the case of ${\mathcal{L}}^2$ convergence and then by Birkhoff in the much stronger case of pointwise convergence which solved the most fundamental question in statistical mechanics: when does the time average converge to the space average? Before getting into this let us think about what [Poincaré Recurrence](\posts\my-first-post\#poincaré’s-recurrence-theorem) gave us:

> Let $T : \mathcal{X} \to \mathcal{X}$ be a measure-preserving transformation of a probability space $(\mathcal{X}, \beta, \mu)$. Let $\mathcal{E} \in \beta$ with $m(\mathcal{E}) > 0$. Then almost all points of $\mathcal{E}$ return infinitely often to $\mathcal{E}$ under positive iteration by $T$ (i.e., there exists $\mathcal{F} \subseteq \mathcal{E}$ with $m(\mathcal{F}) = m(\mathcal{E})$ such that for each $x \in \mathcal{F}$ there is a sequence $n_1 < n_2 < n_3 < \cdots$ of natural numbers with $T^{n_i}(x) \in \mathcal{F}$ for each $i$).

So, if we have a [measure preserving system](\posts\my-first-post\#measure-preserving-systems), then we can take a measurable set $\mathcal{E}$ with a point $x \in \mathcal{E}$ which returns infinitely often to $\mathcal{E}$. Poincaré Recurrence guarantees the existence of such a point. What we want to find now is in some sense: the frequency of the occurence of the points of the orbit of $x$ in $\mathcal{E}$. 

Let $\mathcal{O}(x) = \{ x, T(x), T^2(x), \dots \}$ be the orbit of $x \in \mathcal{E}$. Let $\mathcal{O}_N(x) := \{ x, \dots , T^{N-1}(x) \}$

The frequency of the number of points of $\mathcal{O}_N(x)$ that are also in $E$ can be represented as follows:
$$ \frac{1}{N} \sum_{i=0}^{N-1} X_E(T^i(x)), $$
where $X_E$ is the characteristic function of $E$. Now what would happen if $N$ keeps increasing? Consider the following limit:
$$ \lim_{N \to \infty} \frac{1}{N} \sum_{i=0}^{N-1} X_E(T^i(x)) $$
Some questions we may have are: Will such a limit exist in the first place? Under what condidtions can such a limit exist? Incase it does, what can it possibly converge to? 

Let us genralize our problem to an arbitary measurable or integrable function $f$ instead of the characteristic function and call the limit the time average. So now we want to know what could possibly happen to $$ \lim_{N \to \infty} \frac{1}{N} \sum_{i=0}^{N-1} f(T^i(x)) $$

Boltzmann (in a very physics pov perhaps) hypothesized that the time average converges to the space average which is $\int f d\mu$. This is not quite true always which leads us to the Birkhoff's ergodic theorem which says that in the case of an ergodic system, the time average converges to the space average. Let us first understand what an ergodic transformation is.

### Ergodicity

Ergodicity formalizes the idea of when a dynamical system cannot be broken down into smaller invariant pieces with positive measure. Let us first see what an invariant set is:

> Let $T: \mathcal{X} \rightarrow \mathcal{X}$ be a transformation. A subset $\mathcal{B}$ of $\mathcal{X}$ is **invariant** under $T$ if $T^{-1}(\mathcal{B})=\mathcal{B}$.

Note that $T$ need not be invertible here. $T^{-1}(\mathcal{B})$ just refers to all the points in $\mathcal{X}$ that $T$ takes to $\mathcal{B}$. Now we can define what an ergodic transformation is.

> A measure preserving transformation T on a probability space is **ergodic** if for every $T$-invariant set $\mathcal{B}$ in $\beta$, either $\mu(\mathcal{B})=0$ or $\mu(\mathcal{B})=1$. 

In other words, the system is measure-theoretically indecomposable i.e: any invariant set is either negligible or occupies the whole space.

**Example:** Consider a rational rotation on the following set $\mathcal{A}$ in $\mathbb{R}/\mathbb{Z}$. 
$$
\mathcal{A} = \bigcup_{i=0}^{q-1} \left[ \frac{i}{q},\frac{i}{q}+\frac{1}{2q}\right].
$$
This set is invariant under $R_\alpha$ as it sends each interval in $\mathcal{A}$ into another one in $\mathcal{A}$ itself but the measure of this set lies between $0$ and $1$ making it non-ergodic. Turns out, irrational rotations are ergodic which we will probably look into in another post (along with more consequences of ergodicity).

We are now ready to state the Birkhoff's ergodic theorem. Note that we restrict ourselves to a probability space since any finite measure space can be normalized accordingly.

### The Birkhoff's Ergodic Theorem

> Let $(\mathcal{X},\beta,\mu)$ be a probability space and let $T$ be an ergodic transformation on $(\mathcal{X},\beta,\mu)$. If $f: \mathcal{X} \to \mathbb{R}$ is an integrable function, then for $\mu$-a.e $x \in \mathcal{X}$
> $$
    \lim_{n \to \infty} \frac{1}{n} \sum_{i=0}^{n-1} f(T^i(x)) = \int f d\mu 
  $$

### Can ergodicity be relaxed?

Now, what happens if we do not have an ergodic system? Turns out, in the case of measure-preserving systems, the time average does converge, not to the space average, but to a $T$-invariant function as stated below and we can also very easily find the integral of this limit function.

> Let $(\mathcal{X},\beta,\mu)$ be a probability space and let $T$ be a measure-preserving transformation on $(\mathcal{X},\beta,\mu)$. If $f: \mathcal{X} \to \mathbb{R}$ is an integrable function, then  

> 1. $\lim_{n \to \infty} \frac{1}{n} \sum_{i=0}^{n-1} f(T^i(x))$ exists for a.e $x \in \mathcal{X}$. Denote this limit by $\bar{f}(x)$.  
> 2. $\bar{f}(Tx) = \bar{f}(x)$ a.e.  
> 3. For any measurable set $\mathcal{A}$ that is $T$-invariant,  
>    \begin{equation*}
        \int_{\mathcal{A}} f d\mu = \int_{\mathcal{A}} \bar{f} d\mu.
    \end{equation*}

The proof is quite lengthy and I am skipping it here. One can refer to [@silva2008] for a beginner-friendly proof. One can also refer to [@assani2003wiener] which has 3 very interesting proofs (one using the maximal inequality, one using a combinatorial argument and the last using a variational inequality) which are a little advanced.



::: {.comment-section}
<!-- Giscus comments widget -->
<script src="https://giscus.app/client.js"
        data-repo="MostlyMath/MostlyMathematics"
        data-repo-id="R_kgDOPrVY4w"
        data-category="Comments"
        data-category-id="DIC_kwDOPrVY484CvwcT"
        data-mapping="url"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="light"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>
:::
